// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: prototpl/person-service/person-service.proto

package servicev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PersonMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PersonMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PersonMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PersonMessageMultiError, or
// nil if none found.
func (m *PersonMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *PersonMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Age

	if len(errors) > 0 {
		return PersonMessageMultiError(errors)
	}

	return nil
}

// PersonMessageMultiError is an error wrapping multiple validation errors
// returned by PersonMessage.ValidateAll() if the designated constraints
// aren't met.
type PersonMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PersonMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PersonMessageMultiError) AllErrors() []error { return m }

// PersonMessageValidationError is the validation error returned by
// PersonMessage.Validate if the designated constraints aren't met.
type PersonMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PersonMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PersonMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PersonMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PersonMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PersonMessageValidationError) ErrorName() string { return "PersonMessageValidationError" }

// Error satisfies the builtin error interface
func (e PersonMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPersonMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PersonMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PersonMessageValidationError{}
